# Log Level: [OFF, SEVERE, WARNING, INFO, CONFIG, FINE, FINER, FINEST, ALL]
LoggerLevel: "INFO"
# Date formatting
TimeFormat: yyyy/MM/dd HH:mm
# Engine selection: JS engine is used by default, this plugin does not come with an engine module, to disable it you can delete this line
ScriptEngine: js
# Global protection NBT list [Protect the following NBT from being changed during auto-updates]
ProtectNBT:
  - "protect.data"
# If inventory is full when giving items, they will drop [Simple pickup protection, only protects player's pickups]
GiveOverflowDrop: true
# SX-Items dropped by epic monsters go directly into player's inventory
MobDropToPlayerInventory: true
